
import Link from 'next/link';
import Image from 'next/image';

export default function PrivacyPolicyPage() {
  return (
    <div className="flex flex-col min-h-screen bg-background">
      <header className="px-4 lg:px-6 h-14 flex items-center sticky top-0 z-50 bg-background/80 backdrop-blur-sm">
        <Link href="/" className="flex items-center justify-center font-bold text-xl" prefetch={false}>
          <Image src="/img/Azmaai logo.png" alt="AzmaAI Logo" width={24} height={24} className="mr-2" />
          <span>AZMA AI</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link href="/login" className="text-sm font-medium hover:underline underline-offset-4" prefetch={false}>
            Login
          </Link>
          <Link
            href="/signup"
            className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
            prefetch={false}
          >
            Get Started
          </Link>
        </nav>
      </header>
      <main className="flex-1">
        <section
          className="relative w-full py-12 md:py-24 lg:py-32 bg-cover bg-center bg-fixed"
          style={{
            backgroundImage: `url('https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExMXRtcWpjdmxqd29nOHJqdTRlYzZtczRmdW4wYWNkZ3c0OGl4M3VtNyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/ITRemFlr5tS39AzQUL/giphy.gif')`,
          }}
        >
          <div className="absolute inset-0 bg-black/60 z-0" />
          <div className="relative z-10 container px-4 md:px-6 text-center text-white">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl">Privacy Policy</h1>
            <p className="max-w-[700px] mx-auto text-gray-200 md:text-xl mt-4">
              Last Updated: July 30, 2024
            </p>
          </div>
        </section>

        <section className="w-full py-12 md:py-24 lg:py-32 bg-background/90">
          <div className="container px-4 md:px-6 prose prose-lg dark:prose-invert max-w-4xl mx-auto">
            <h2>1. Introduction</h2>
            <p>
              Welcome to AzmaAI ("we," "our," "us"). We are committed to protecting your privacy. This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you use our web application (the "Service"). Please read this policy carefully. If you do not agree with the terms of this privacy policy, please do not access the Service.
            </p>

            <h2>2. Information We Collect</h2>
            <p>We may collect information about you in a variety of ways. The information we may collect via the Service includes:</p>
            <h3>Personal Data</h3>
            <p>
              Personally identifiable information, such as your name, email address, phone number, and demographic information (like your role as a student, teacher, etc.), that you voluntarily give to us when you register for the Service or when you choose to participate in various activities related to the Service.
            </p>
            <h3>Generated Content</h3>
            <p>
              Any inputs you provide to our AI models (such as topics, parameters, and questions) and the academic content generated by the AI (including text, references, images, and other data) are processed and stored to provide and improve the service. Your documents and projects are stored in your private workspace.
            </p>
            <h3>Financial Data</h3>
            <p>
              Financial information, such as data related to your payment method (e.g., valid credit card number, card brand, expiration date) that we may collect when you purchase, order, return, exchange, or request information about our services from the Service. We store only very limited, if any, financial information that we collect. Otherwise, all financial information is stored by our payment processor, Flutterwave, and you are encouraged to review their privacy policy and contact them directly for responses to your questions.
            </p>
            <h3>Data From Third-Party Services</h3>
            <p>
                We may collect information from third-party services like Google when you use your Google account to sign in. This information may include your name, email address, and profile picture.
            </p>
            <h3>Usage Data</h3>
            <p>
              Information our servers automatically collect when you access the Service, such as your IP address, browser type, operating system, access times, and the pages you have viewed directly before and after accessing the Service.
            </p>

            <h2>3. How We Use Your Information</h2>
            <p>Having accurate information about you permits us to provide you with a smooth, efficient, and customized experience. Specifically, we may use information collected about you via the Service to:</p>
            <ul>
              <li>Create and manage your account.</li>
              <li>Process your payments and subscriptions.</li>
              <li>Generate and deliver academic content as requested.</li>
              <li>Email you regarding your account or order.</li>
              <li>Monitor and analyze usage and trends to improve your experience with the Service.</li>
              <li>Notify you of updates to the Service.</li>
              <li>Prevent fraudulent transactions, monitor against theft, and protect against criminal activity.</li>
              <li>Respond to customer service requests.</li>
            </ul>
            
            <h2>4. AI and Data Processing</h2>
            <p>
                The content you submit for generation is processed by third-party AI models (such as Google's Gemini). We do not use your generated documents or personal data to train our own models. However, the data sent to third-party AI providers may be subject to their respective data usage policies. We strive to use providers that prioritize data privacy.
            </p>

            <h2>5. Disclosure of Your Information</h2>
            <p>We may share information we have collected about you in certain situations. Your information may be disclosed as follows:</p>
            <ul>
              <li>
                <strong>By Law or to Protect Rights:</strong> If we believe the release of information about you is necessary to respond to legal process, to investigate or remedy potential violations of our policies, or to protect the rights, property, and safety of others, we may share your information as permitted or required by any applicable law, rule, or regulation.
              </li>
              <li>
                <strong>Third-Party Service Providers:</strong> We may share your information with third parties that perform services for us or on our behalf, including payment processing (Flutterwave), data analysis, email delivery, hosting services (Firebase), customer service, and AI model provisioning (Google AI).
              </li>
            </ul>

            <h2>6. Data Security</h2>
            <p>
              We use administrative, technical, and physical security measures to help protect your personal information. While we have taken reasonable steps to secure the personal information you provide to us, please be aware that despite our efforts, no security measures are perfect or impenetrable, and no method of data transmission can be guaranteed against any interception or other type of misuse.
            </p>
            
            <h2>7. Your Data Rights</h2>
            <p>You have the right to:</p>
            <ul>
                <li>Access the personal data we hold about you.</li>
                <li>Request that we correct any inaccurate personal data.</li>
                <li>Request that we delete your personal data.</li>
                <li>Manage your workspace data, including deleting or archiving projects and documents, directly within the application.</li>
            </ul>
            <p>To exercise these rights, please contact us using the contact information provided below.</p>
            
            <h2>8. Children's Privacy</h2>
            <p>
              Our Service is not intended for use by children under the age of 13. We do not knowingly collect personal information from children under 13. If we become aware that a child under 13 has provided us with personal information, we will take steps to delete such information.
            </p>

            <h2>9. Changes to This Privacy Policy</h2>
            <p>
              We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page and updating the "Last Updated" date. You are advised to review this Privacy Policy periodically for any changes.
            </p>

            <h2>10. Contact Us</h2>
            <p>
              If you have questions or comments about this Privacy Policy, please contact us at: <a href="mailto:privacy@azma.ai">privacy@azma.ai</a>.
            </p>
          </div>
        </section>
      </main>
       <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t bg-background/90">
          <p className="text-xs text-muted-foreground">&copy; AzmaAI – Academic Zenith for Manuscripts & Assignments. Sfaret Technologies © 2025</p>
          <nav className="sm:ml-auto flex gap-4 sm:gap-6">
             <Link href="/about" className="text-xs hover:underline underline-offset-4" prefetch={false}>
              About
            </Link>
            <Link href="/#features" className="text-xs hover:underline underline-offset-4" prefetch={false}>
              Features
            </Link>
            <Link href="/#pricing" className="text-xs hover:underline underline-offset-4" prefetch={false}>
              Pricing
            </Link>
            <Link href="/contact" className="text-xs hover:underline underline-offset-4" prefetch={false}>
              Contact
            </Link>
             <Link href="/seal-verify" className="text-xs hover:underline underline-offset-4" prefetch={false}>
              SEAL Verify
            </Link>
             <Link href="/privacy-policy" className="text-xs hover:underline underline-offset-4" prefetch={false}>
              Privacy Policy
            </Link>
          </nav>
        </footer>
    </div>
  );
}
